// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_door_lock_req                   11
#define gattdb_door_lock_state                 14
#define gattdb_manufacturer_name_string         18
#define gattdb_model_number_string             21
#define gattdb_serial_number_string            24
#define gattdb_firmware_revision_string         27
#define gattdb_device_name                     31
#define gattdb_appearance                      34
#define gattdb_light_state                     38
#define gattdb_trigger_source                  42
#define gattdb_source_address                  46
#define gattdb_ota_control                     51
#define gattdb_ota_data                        53

#endif
