// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include "app/framework/include/af.h"
#include "app/framework/cli/custom-cli.h"
#include EMBER_AF_API_COMMAND_INTERPRETER2

EmberCommandEntry emberCommandTable[] = {
#ifdef EMBER_AF_ENABLE_CUSTOM_COMMANDS
  CUSTOM_COMMANDS
#endif // EMBER_AF_ENABLE_CUSTOM_COMMANDS
  emberCommandEntryTerminator(),
};
